### PR TITLE
include at least one filtered marker in view

### LINKED ISSUE #179: if users filter by species/family and no trees of that species in the current view, zoom out map view to include filtered species/family
**AS A/AN:**
user

**WHEN I**:
use a select2 filter and select one or more tree species

**I WANT TO**:
then see at least one marker (that represents the selected species) on the map

### PR DESCRIPTION
**Pull request by AkaXaphion**
resolves  #179 

# What I did
- Look for the selected marker closest to the center of the current view

- Extends the view to encompass it

### CODE REVIEW

**Comment by emillipede** [comment]
awesome, thank you @AkaXaphion!! I'll merge your contribution now

**Comment by emillipede** [comment]
hey @AkaXaphion I have a question about this old PR. a user asked today if it's possible to keep their zoom level when the select a species (eg, if they are very zoomed in, they'd like to stay zoomed in but moved to a part of the map where a tree in the selected species is visible). please let me know what you think. thank you!

**Comment by AkaXaphion** [comment]
Yes there is a panning function though I had some concerns about it. With the panning animation enabled and set to a reasonable duration, depending on the zoom level and the distance to the target, the map has trouble rendering fast enough such that I can't even tell which direction I'm being brought in since majority of the view is just grey. Maybe a caching plugin is needed?
There's also the option of not having an animation at all but then you'd have to zoom out to find out where on earth you were brought to.

**Comment by emillipede** [comment]
thanks for this explanation @AkaXaphion, your concerns sound reasonable. for now, I think it makes sense to leave the view extension how you've set it.

**Comment by emillipede** [comment]
hey @trxaphion, I have another question about this function.

do you have a recommendation for how to account for the toolbar? sometimes the closest identified marker is hidden behind the toolbar. in those cases, the marker(s) won't be visible to the user. please let me know what you think. thank you

**Comment by trxaphion** [comment]
ah yea that's not an unlikely case with the new toolbar. I found a leaflet method that will help, will PR soon

**Pull request merged**
