### PR TITLE
Mobile view fix

### LINKED ISSUE #245: in mobile view, reduce toolbar white space
as a:
mobile user

when I:
view the map

I want to:
see the map and not have the top toolbar overlap with the map. 

on some displays, the buttons and address bar stick out below the toolbar. 

on some displays, when the mini/preview window is closed, the toolbar becomes unnecessarily tall and occupies a lot of vertical space. it seems like the newer the device, the worse the problem.

might be addressed by defining the map size (to fix/define the toolbar height)?

#### zeplin:
Screen Shot 2019-09-23 at 11 31 05 PM

#### current website (on small iphone SE):
- buttons bleed a little onto the map:
Image from iOS (2)
- toolbar becomes taller than necessary:
Screen Shot 2019-11-07 at 1 57 51 PM

### PR DESCRIPTION
**Pull request by mrtmrt233**
resolves #245 

got rid of weird white spaces with CSS adjustments

### CODE REVIEW

**Comment by emillipede** [comment]
thank you @mrtmrt233 

when I test it, the mobile sidebar now functions cropped in an unexpected way. it seems like the sidebar no longer opens into the full screen. instead - when I click "view details", the sidebar opens in the same mini window and it's cropped in a weird way at the bottom of the map. please take a look.

tested as iphone x
Screen Shot 2020-06-14 at 11 19 55 AM

tested as iphone 5
Screen Shot 2020-06-14 at 11 20 05 AM

**Comment by mrtmrt233** [comment]
oops fixed now

**Comment by emillipede** [comment]
sidebar opens again @mrtmrt233 thanks!

question
do you know why the margins in the mini panel changed? it's most visible in the screenshots of the iphone 5 (the white space above the species name disappeared). 
is it possible to restore the margins? I think the spacing makes the text more difficult to read.

before:
as iphone X:
Screen Shot 2020-06-14 at 12 06 11 PM
as iphone 5:
Screen Shot 2020-06-14 at 12 06 24 PM

after
as iphone 5:
Screen Shot 2020-06-14 at 12 04 53 PM
as iphone X:
Screen Shot 2020-06-14 at 12 05 19 PM

**Comment by emillipede** [comment]
thank you @mrtmrt233 for all of the css wrangling, the height issues look fixed

Screen Shot 2020-06-14 at 12 06 11 PM
Screen Shot 2020-06-14 at 12 06 24 PM

**Pull request merged**
