### PR TITLE
Update/ Address of tree is shown in mobile view

### LINKED ISSUE #226: add tree address to mini/preview sidebar
AS A:
mobile user

WHEN I:
select a tree marker

I WANT TO:
see the tree's street address, as specified by the city (to help determine if I'm looking at the correct tree record)

in the zeplin/design, the tree's street address is included in the mobile mini sidebar/tree preview (the address isn't part of the site)

note - for formatting of this window, see #227

|zeplin|current site|
|---|---|
|Screen Shot 2019-09-23 at 11 31 05 PM|IMG_6260|

### PR DESCRIPTION
**Pull request by sourcediz**
resolves #226

# Motivation and context
When viewing trees in mobile view the address was not show. This PR resolves this issue according to the style design of provided UI example

# Screenshots
| before | after |
|---|---|
| Screen Shot 2019-11-04 at 1 39 24 AM
| 
Screen Shot 2019-11-04 at 1 39 13 AM
|

# What I did
- in the stylesheet sidebar-address was incorrectly referenced as a .class not an #Id so this was corrected
-View Details <button> was moved bellow <div>address</div> in the index.html

#Next Step Recommendation
- Fix scaling issue of View Details Button

### CODE REVIEW

**Comment by emillipede** [comment]
hi @sourcediz, thank you for this improvement and for your recommendation! for the view details button issue, are you describing how the button gets cropped in some mobile browsers?  

question: do you know how complicated it would be to display the address text in a different size?

I didn't include this detail in the issue - the designer specified that the address would be displayed in two different sizes - in the mobile preview, the address would be 11px, and in the full screen sidebar (as well as in the desktop view), it would be 16px. 

mobile preview:
Screen Shot 2019-09-23 at 11 31 05 PM

full screen sidebar:
Screen Shot 2019-11-04 at 1 41 04 PM

thank you again!

**Comment by sourcediz** [comment]
This PR implements font-size change now as per requested.
With the view details button without it being responsive it looks quite small on some phones but this is only what i Know from viewing it through inspector not on actual devices. For example on iphone x (see 2nd pic related )

Screen Shot 2019-11-06 at 2 38 26 AM

Iphone X
Screen Shot 2019-11-06 at 2 42 24 AM

**Comment by emillipede** [comment]
@sourcediz thank you again for your contribution! I'll try to update the PR from master so that I can merge your changes in mobile.css into the new sidebar.css file

your suggestion about scaling the view details button size makes a lot of sense, thanks for bringing it up. if you'd like to tackle the problem, you're more than welcome to go for it. so far, my primary concern with the button had been when it appears too big/gets cropped on small devices

**Comment by sourcediz** [comment]
Sorry didn't realise there was conflicting files Ill fix that up real quick

**Comment by sourcediz** [comment]
Okay now PR is ready to be merged. With the button ill do some further research to see how it actually looks like in person. Ill also look into this cropping you have mentioned.
Always glad to help with green projects like this :)

**Comment by emillipede** [comment]
thank you @sourcediz for your help and your interest, I really appreciate it! 

I'm sorry for the delay in my reply and in merging your changes

thank you again!!!

**Pull request merged**
