### PR TITLE
Add link to hertiage nomination google form in sidebar

### LINKED ISSUE #204: add heritage tree nomination form/link
**AS A/AN**:
user

**WHEN I**:
see an amazing tree

**I WANT TO**:
have the option to nominate the tree as a heritage tree (maybe through a button in the sidebar)

**AS A/AN**:
SM public landscape

**I WANT TO**:
encourage community members' participation in and awareness of the heritage tree program

right now, the city's nomination process isn't well known and less than user-friendly. it requires modifying a PDF or sending a letter. an easier nominations process might encourage more participation in the program (https://www.smgov.net/Portals/UrbanForest/content.aspx?id=53687092939)

until we have a webform, we could just link to the city's heritage tree program website

### PR DESCRIPTION
**Pull request by isabelle-wagenvoord**
resolves #204 

# What I did
- Add a link in the sidebar to the google form @emillipede created

### CODE REVIEW

**Comment by emillipede** [comment]
thank you @isabelle-wagenvoord !

could you please move this link to fit the format in the main body of the sidebar?

It'd work as a section right below (or above? what do you think?) the "Report an Issue" section

- header: Nominate Tree
 - text: Impressed by this tree? Please nominate it for city recognition as a Santa Monica Heritage Tree via [this form](https://forms.gle/UDjd8CS4w2jMu8As8).

**Comment by isabelle-wagenvoord** [comment]
@emillipede I put it above the "Report an issue" section for now, but it's your call.

**Comment by emillipede** [comment]
thank you @isabelle-wagenvoord !

**Comment by emillipede** [comment]
@isabelle-wagenvoord 

question - can you please update the index.html so that this section is hidden for the existing heritage trees? 

I'm sorry I didn't think of it sooner. I'll open a new issue

**Comment by isabelle-wagenvoord** [comment]
@emillipede Right! I'll do that.

**Pull request merged**
